-- CreateTable
CREATE TABLE "packs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "price" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "packs_pkey" PRIMARY KEY ("id")
);

-- AlterTable
ALTER TABLE "couples" ADD COLUMN "pack_id" BIGINT;

-- Data migration from legacy couples.pack values
INSERT INTO "packs" ("name", "description", "price")
SELECT 'Simple', 'Pack migrado automaticamente', 0
WHERE EXISTS (
    SELECT 1
    FROM "couples"
    WHERE "pack" = '0'
) AND NOT EXISTS (
    SELECT 1
    FROM "packs"
    WHERE LOWER("name") = 'simple'
);

INSERT INTO "packs" ("name", "description", "price")
SELECT 'Completo', 'Pack migrado automaticamente', 0
WHERE EXISTS (
    SELECT 1
    FROM "couples"
    WHERE "pack" = '1'
) AND NOT EXISTS (
    SELECT 1
    FROM "packs"
    WHERE LOWER("name") = 'completo'
);

INSERT INTO "packs" ("name", "description", "price")
SELECT DISTINCT c."pack", 'Pack migrado automaticamente', 0
FROM "couples" c
WHERE c."pack" IS NOT NULL
  AND BTRIM(c."pack") <> ''
  AND c."pack" NOT IN ('0', '1')
  AND NOT EXISTS (
      SELECT 1
      FROM "packs" p
      WHERE LOWER(p."name") = LOWER(c."pack")
  );

UPDATE "couples"
SET "pack_id" = (
    SELECT p."id"
    FROM "packs" p
    WHERE LOWER(p."name") = 'simple'
    LIMIT 1
)
WHERE "pack" = '0';

UPDATE "couples"
SET "pack_id" = (
    SELECT p."id"
    FROM "packs" p
    WHERE LOWER(p."name") = 'completo'
    LIMIT 1
)
WHERE "pack" = '1';

UPDATE "couples" c
SET "pack_id" = (
    SELECT p."id"
    FROM "packs" p
    WHERE LOWER(p."name") = LOWER(c."pack")
    LIMIT 1
)
WHERE c."pack_id" IS NULL
  AND c."pack" IS NOT NULL
  AND BTRIM(c."pack") <> '';

ALTER TABLE "couples" DROP COLUMN "pack";

-- CreateIndex
CREATE INDEX "couples_pack_id_idx" ON "couples"("pack_id");

-- AddForeignKey
ALTER TABLE "couples" ADD CONSTRAINT "couples_pack_id_fkey" FOREIGN KEY ("pack_id") REFERENCES "packs"("id") ON DELETE SET NULL ON UPDATE CASCADE;

